load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "heratio-demo",
    srcs = ["heratio-demo.cc"],
    deps = [
      "//lib:heratio",
      "@ntl//:ntl_",
      "@gmp//:gmp_",
      ],
)